name: Towny
main: ca.xshade.bukkit.towny.Towny
version: 2.0.44
author: Shade
website: http://towny.xshade.ca
description: >
    Resident-Town-Nation heirarchy combined with a grid based
    protection system. Including a war event.
commands:
    towny:
        description: Basic towny commands.